### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by msamoylov** [jbarone/ghostToHugo#23]
**Describe the bug**

```
$ go version
go version go1.13 darwin/amd64
$ go get -u github.com/jbarone/ghostToHugo
# github.com/jbarone/ghostToHugo/lib
../../go/src/github.com/jbarone/ghostToHugo/lib/ghostToHugo.go:174:20: site.NewPage undefined (type *hugolib.Site has no field or method NewPage)
../../go/src/github.com/jbarone/ghostToHugo/lib/ghostToHugo.go:181:4: undefined: parser.FormatToLeadRune
```

**Comment by jbarone** [comment]
I'm sorry it's not building. 

Looks like there are few things going on. Hugo has changed some things on me, which normally shouldn't be an issue since the go.mod should lock to a particular version of Hugo. Your build doesn't seem to have go modules turned on, which I'll have to update the docs to show how to do that. I just tried to build both with and without go modules, and I'm seeing fails in both. I don't have time to get to this today, but I should hopefully have it resolved by tomorrow. 

Meanwhile, if you need to you can just download one of the pre-built versions and that should get you up and running.

**Comment by jbarone** [comment]
@msamoylov The new rewritten version is up. Should be able to build now. Please let me know if you are still having issues.
